gtnh.settings.blowdryerTag = 0.2.2
gtnh.modules.codeStyle = false
modName = MalisisDoors
modId = malisisdoors
modGroup = net.malisis
modVersion = 1.7.10-1.13.2
useModGroupForPublishing = true
customArchiveBaseName = malisisdoors
autoUpdateBuildScript = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

enableModernJavaSyntax = false
enableGenericInjection = true

generateGradleTokenClass = net.malisis.doors.Tags
gradleTokenVersion = VERSION
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
includeWellKnownRepositories = true
usesMavenPublishing = false
runDir = eclipse
developmentEnvironmentUserName =
